name: Test, Build, and Deploy | Modul 01 - Lab2.2 Senior Project

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run build

  deploy:
    needs: test-build
    runs-on: ubuntu-latest

    steps:
      - name: Build app on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/ssh-praktikan25

            # Check Node Version
            echo "Current Node Version:"
            node -v || echo "Node.js not installed."

            # Install NVM (Node Version Manager) if not installed
            if [ ! -d "$HOME/.nvm" ]; then
              echo "Installing NVM..."
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            fi

            # Load NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Install Node.js 16
            echo "Installing Node.js 16..."
            nvm install 16
            nvm use 16
            echo "Node.js version after install:"
            node -v

            echo "Cek folder project"
            [ ! -d "${HOME}/senpro/503299/modul02/senpro-github-action/" ] &&
              {
                echo "Repository belum di-clone. Cloning...";
                mkdir -p ~/senpro/503299/modul02;
                cd ~/senpro/503299/modul02;
                git clone https://github.com/queredda/senpro-github-action.git
                cd ~/senpro/503299/modul02/senpro-github-action;
                echo "Install Package and Build Project";
                npm install;
                npm run build;
              } ||
              {
                echo "Repository sudah ada. Building...";
                cd ~/senpro/503299/modul02/senpro-github-action;
                git restore .;
                git pull origin main;
                echo "Install Package and Build Project";
                npm install;
                npm run build;
              }
